# Generated by Django 3.0.5 on 2020-04-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=32)),
                ('firstname', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('tel', models.IntegerField()),
                ('service', models.CharField(max_length=32)),
                ('image', models.FileField(upload_to='')),
                ('date_e', models.DateTimeField()),
                ('date_s', models.DateTimeField()),
            ],
        ),
    ]
