# Generated by Django 3.0.5 on 2020-04-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0003_auto_20200416_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_e',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
