# Generated by Django 3.0.5 on 2020-04-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0005_auto_20200416_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
