# Generated by Django 3.0.5 on 2020-05-03 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0006_auto_20200417_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pwd',
        ),
    ]
