# Generated by Django 3.0.5 on 2020-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myap', '0007_remove_user_pwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default='django', max_length=32),
        ),
    ]
